language: csharp
dist: trusty
mono: none
dotnet: 1.0.4

install:
- dotnet restore

script:
- dotnet build HelloWorldDevops/HelloWorldDevops.csproj
- dotnet build XUnitTestProject/XUnitTestProject.csproj
- dotnet test XUnitTestProject/XUnitTestProject.csproj
