version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build HelloWorldDevops/HelloWorldDevops.csproj
      - run: dotnet build XUnitTestProject/XUnitTestProject.csproj
      - run: dotnet test XUnitTestProject/XUnitTestProject.csproj
  deployment:
   branch: master
    heroku:
      appname: my-frist-app-hw
